[package]
name = "zsx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.48.0", features = ["time"] }
rand = "0.10.0-rc.0"

[dev-dependencies]
mockall = "0.13.1"